// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: companies.sql

package database

import (
	"context"
	"database/sql"
)

const countCompanies = `-- name: CountCompanies :one
SELECT COUNT(*) FROM companies
`

// Get total count of companies
func (q *Queries) CountCompanies(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompanies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (name, website)
VALUES ($1, $2)
RETURNING id, name, website, created_at, updated_at, user_id
`

type CreateCompanyParams struct {
	Name    string         `json:"name"`
	Website sql.NullString `json:"website"`
}

// Create a new company and return the created record
func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany, arg.Name, arg.Website)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM companies
WHERE id = $1
`

// Delete a company by ID
func (q *Queries) DeleteCompany(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCompany, id)
	return err
}

const getAllCompanies = `-- name: GetAllCompanies :many
SELECT id, name, website, created_at, updated_at, user_id FROM companies
ORDER BY name ASC
`

// Get all companies, ordered by name
func (q *Queries) GetAllCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, getAllCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCompaniesPaginated = `-- name: GetAllCompaniesPaginated :many
SELECT id, name, website, created_at, updated_at, user_id FROM companies
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type GetAllCompaniesPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Get paginated companies, ordered by name
func (q *Queries) GetAllCompaniesPaginated(ctx context.Context, arg GetAllCompaniesPaginatedParams) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, getAllCompaniesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, name, website, created_at, updated_at, user_id FROM companies
WHERE id = $1
`

// Get a single company by ID
func (q *Queries) GetCompanyByID(ctx context.Context, id int32) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getCompanyByName = `-- name: GetCompanyByName :one
SELECT id, name, website, created_at, updated_at, user_id FROM companies
WHERE LOWER(TRIM(name)) = LOWER(TRIM($1))
LIMIT 1
`

// Get a company by name (case-insensitive, for normalization check)
// This query uses normalized comparison to check if a company exists
func (q *Queries) GetCompanyByName(ctx context.Context, btrim string) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByName, btrim)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET name = $2,
    website = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, website, created_at, updated_at, user_id
`

type UpdateCompanyParams struct {
	ID      int32          `json:"id"`
	Name    string         `json:"name"`
	Website sql.NullString `json:"website"`
}

// Update a company and return the updated record
func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, updateCompany, arg.ID, arg.Name, arg.Website)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
