// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: companies.sql

package database

import (
	"context"
	"database/sql"
)

const countCompaniesByUserID = `-- name: CountCompaniesByUserID :one
SELECT COUNT(*) FROM companies
WHERE user_id = $1
`

// Get total count of companies for a specific user
func (q *Queries) CountCompaniesByUserID(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompaniesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (name, website, user_id)
VALUES ($1, $2, $3)
RETURNING id, name, website, created_at, updated_at, user_id
`

type CreateCompanyParams struct {
	Name    string         `json:"name"`
	Website sql.NullString `json:"website"`
	UserID  int32          `json:"user_id"`
}

// Create a new company and return the created record
func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany, arg.Name, arg.Website, arg.UserID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM companies
WHERE id = $1 AND user_id = $2
`

type DeleteCompanyParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

// Delete a company by ID (verifies ownership via user_id)
func (q *Queries) DeleteCompany(ctx context.Context, arg DeleteCompanyParams) error {
	_, err := q.db.ExecContext(ctx, deleteCompany, arg.ID, arg.UserID)
	return err
}

const getCompaniesByUserID = `-- name: GetCompaniesByUserID :many
SELECT id, name, website, created_at, updated_at, user_id FROM companies
WHERE user_id = $1
ORDER BY name ASC
`

// Get all companies for a specific user, ordered by name
func (q *Queries) GetCompaniesByUserID(ctx context.Context, userID int32) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, getCompaniesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompaniesByUserIDPaginated = `-- name: GetCompaniesByUserIDPaginated :many
SELECT id, name, website, created_at, updated_at, user_id FROM companies
WHERE user_id = $1
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type GetCompaniesByUserIDPaginatedParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Get paginated companies for a specific user, ordered by name
func (q *Queries) GetCompaniesByUserIDPaginated(ctx context.Context, arg GetCompaniesByUserIDPaginatedParams) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, getCompaniesByUserIDPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompanyByIDAndUserID = `-- name: GetCompanyByIDAndUserID :one
SELECT id, name, website, created_at, updated_at, user_id FROM companies
WHERE id = $1 AND user_id = $2
`

type GetCompanyByIDAndUserIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

// Get a single company by ID and user_id (ownership verification)
func (q *Queries) GetCompanyByIDAndUserID(ctx context.Context, arg GetCompanyByIDAndUserIDParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByIDAndUserID, arg.ID, arg.UserID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getCompanyByNameAndUserID = `-- name: GetCompanyByNameAndUserID :one
SELECT id, name, website, created_at, updated_at, user_id FROM companies
WHERE LOWER(TRIM(name)) = LOWER(TRIM($1)) AND user_id = $2
LIMIT 1
`

type GetCompanyByNameAndUserIDParams struct {
	Btrim  string `json:"btrim"`
	UserID int32  `json:"user_id"`
}

// Get a company by name and user_id (case-insensitive, for normalization check)
// This query uses normalized comparison to check if a company exists for a specific user
func (q *Queries) GetCompanyByNameAndUserID(ctx context.Context, arg GetCompanyByNameAndUserIDParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByNameAndUserID, arg.Btrim, arg.UserID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET name = $2,
    website = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $4
RETURNING id, name, website, created_at, updated_at, user_id
`

type UpdateCompanyParams struct {
	ID      int32          `json:"id"`
	Name    string         `json:"name"`
	Website sql.NullString `json:"website"`
	UserID  int32          `json:"user_id"`
}

// Update a company and return the updated record (verifies ownership via user_id)
func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.Website,
		arg.UserID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
