// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: contacts.sql

package database

import (
	"context"
	"database/sql"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (name, email, phone, linkedin)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, phone, linkedin, created_at, updated_at, user_id
`

type CreateContactParams struct {
	Name     string         `json:"name"`
	Email    sql.NullString `json:"email"`
	Phone    sql.NullString `json:"phone"`
	Linkedin sql.NullString `json:"linkedin"`
}

// Create a new contact and return the created record
func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, createContact,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Linkedin,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Linkedin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts WHERE id = $1
`

// Delete a contact by ID
func (q *Queries) DeleteContact(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteContact, id)
	return err
}

const getAllContacts = `-- name: GetAllContacts :many
SELECT id, name, email, phone, linkedin, created_at, updated_at, user_id FROM contacts ORDER BY name ASC
`

// Get all contacts ordered by name
func (q *Queries) GetAllContacts(ctx context.Context) ([]Contact, error) {
	rows, err := q.db.QueryContext(ctx, getAllContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Linkedin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactByID = `-- name: GetContactByID :one
SELECT id, name, email, phone, linkedin, created_at, updated_at, user_id FROM contacts WHERE id = $1
`

// Get a contact by ID
func (q *Queries) GetContactByID(ctx context.Context, id int32) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getContactByID, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Linkedin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET name = $2,
    email = $3,
    phone = $4,
    linkedin = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, email, phone, linkedin, created_at, updated_at, user_id
`

type UpdateContactParams struct {
	ID       int32          `json:"id"`
	Name     string         `json:"name"`
	Email    sql.NullString `json:"email"`
	Phone    sql.NullString `json:"phone"`
	Linkedin sql.NullString `json:"linkedin"`
}

// Update a contact and return the updated record
func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, updateContact,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Linkedin,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Linkedin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
