// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: contacts.sql

package database

import (
	"context"
	"database/sql"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (name, email, phone, linkedin, user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, phone, linkedin, created_at, updated_at, user_id
`

type CreateContactParams struct {
	Name     string         `json:"name"`
	Email    sql.NullString `json:"email"`
	Phone    sql.NullString `json:"phone"`
	Linkedin sql.NullString `json:"linkedin"`
	UserID   int32          `json:"user_id"`
}

// Create a new contact and return the created record
func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, createContact,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Linkedin,
		arg.UserID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Linkedin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts
WHERE id = $1 AND user_id = $2
`

type DeleteContactParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

// Delete a contact by ID (verifies ownership via user_id)
func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) error {
	_, err := q.db.ExecContext(ctx, deleteContact, arg.ID, arg.UserID)
	return err
}

const getContactByIDAndUserID = `-- name: GetContactByIDAndUserID :one
SELECT id, name, email, phone, linkedin, created_at, updated_at, user_id FROM contacts
WHERE id = $1 AND user_id = $2
`

type GetContactByIDAndUserIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

// Get a contact by ID and user_id (ownership verification)
func (q *Queries) GetContactByIDAndUserID(ctx context.Context, arg GetContactByIDAndUserIDParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getContactByIDAndUserID, arg.ID, arg.UserID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Linkedin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getContactsByUserID = `-- name: GetContactsByUserID :many
SELECT id, name, email, phone, linkedin, created_at, updated_at, user_id FROM contacts
WHERE user_id = $1
ORDER BY name ASC
`

// Get all contacts for a specific user, ordered by name
func (q *Queries) GetContactsByUserID(ctx context.Context, userID int32) ([]Contact, error) {
	rows, err := q.db.QueryContext(ctx, getContactsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Linkedin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET name = $2,
    email = $3,
    phone = $4,
    linkedin = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $6
RETURNING id, name, email, phone, linkedin, created_at, updated_at, user_id
`

type UpdateContactParams struct {
	ID       int32          `json:"id"`
	Name     string         `json:"name"`
	Email    sql.NullString `json:"email"`
	Phone    sql.NullString `json:"phone"`
	Linkedin sql.NullString `json:"linkedin"`
	UserID   int32          `json:"user_id"`
}

// Update a contact and return the updated record (verifies ownership via user_id)
func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, updateContact,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Linkedin,
		arg.UserID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Linkedin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
