// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: jobs.sql

package database

import (
	"context"
	"database/sql"
)

const countJobsByUserID = `-- name: CountJobsByUserID :one
SELECT COUNT(*) FROM jobs j
INNER JOIN applications a ON j.application_id = a.id
WHERE a.user_id = $1
`

// Get total count of jobs for a specific user (through applications)
func (q *Queries) CountJobsByUserID(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (application_id, company_id, title, description, requirements, location)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, title, description, requirements, location, created_at, updated_at, application_id
`

type CreateJobParams struct {
	ApplicationID int32          `json:"application_id"`
	CompanyID     int32          `json:"company_id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	Requirements  sql.NullString `json:"requirements"`
	Location      sql.NullString `json:"location"`
}

// Create a new job and return the created record
// Jobs now belong to applications (application_id is required)
// Note: user_id verification happens in handler by checking application ownership
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.ApplicationID,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.Requirements,
		arg.Location,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Requirements,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApplicationID,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE jobs.id = $1
  AND EXISTS (
    SELECT 1 FROM applications a
    WHERE a.id = jobs.application_id AND a.user_id = $2
  )
`

type DeleteJobParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

// Delete a job by ID (verifies ownership through application's user_id)
func (q *Queries) DeleteJob(ctx context.Context, arg DeleteJobParams) error {
	_, err := q.db.ExecContext(ctx, deleteJob, arg.ID, arg.UserID)
	return err
}

const getJobByIDAndUserID = `-- name: GetJobByIDAndUserID :one
SELECT j.id, j.company_id, j.title, j.description, j.requirements, j.location, j.created_at, j.updated_at, j.application_id FROM jobs j
INNER JOIN applications a ON j.application_id = a.id
WHERE j.id = $1 AND a.user_id = $2
`

type GetJobByIDAndUserIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

// Get a single job by ID and verify ownership through application's user_id
func (q *Queries) GetJobByIDAndUserID(ctx context.Context, arg GetJobByIDAndUserIDParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByIDAndUserID, arg.ID, arg.UserID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Requirements,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApplicationID,
	)
	return i, err
}

const getJobsByApplicationIDAndUserID = `-- name: GetJobsByApplicationIDAndUserID :many
SELECT j.id, j.company_id, j.title, j.description, j.requirements, j.location, j.created_at, j.updated_at, j.application_id FROM jobs j
INNER JOIN applications a ON j.application_id = a.id
WHERE j.application_id = $1 AND a.user_id = $2
ORDER BY j.created_at DESC
`

type GetJobsByApplicationIDAndUserIDParams struct {
	ApplicationID int32 `json:"application_id"`
	UserID        int32 `json:"user_id"`
}

// Get all jobs for a specific application and verify ownership through application's user_id
func (q *Queries) GetJobsByApplicationIDAndUserID(ctx context.Context, arg GetJobsByApplicationIDAndUserIDParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getJobsByApplicationIDAndUserID, arg.ApplicationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Requirements,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsByCompanyIDAndUserID = `-- name: GetJobsByCompanyIDAndUserID :many
SELECT j.id, j.company_id, j.title, j.description, j.requirements, j.location, j.created_at, j.updated_at, j.application_id FROM jobs j
INNER JOIN applications a ON j.application_id = a.id
WHERE j.company_id = $1 AND a.user_id = $2
ORDER BY j.created_at DESC
`

type GetJobsByCompanyIDAndUserIDParams struct {
	CompanyID int32 `json:"company_id"`
	UserID    int32 `json:"user_id"`
}

// Get all jobs for a specific company and user (through applications)
func (q *Queries) GetJobsByCompanyIDAndUserID(ctx context.Context, arg GetJobsByCompanyIDAndUserIDParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getJobsByCompanyIDAndUserID, arg.CompanyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Requirements,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsByUserID = `-- name: GetJobsByUserID :many
SELECT j.id, j.company_id, j.title, j.description, j.requirements, j.location, j.created_at, j.updated_at, j.application_id FROM jobs j
INNER JOIN applications a ON j.application_id = a.id
WHERE a.user_id = $1
ORDER BY j.created_at DESC
`

// Get all jobs for a specific user (through applications), ordered by created_at (newest first)
func (q *Queries) GetJobsByUserID(ctx context.Context, userID int32) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getJobsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Requirements,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsByUserIDPaginated = `-- name: GetJobsByUserIDPaginated :many
SELECT j.id, j.company_id, j.title, j.description, j.requirements, j.location, j.created_at, j.updated_at, j.application_id FROM jobs j
INNER JOIN applications a ON j.application_id = a.id
WHERE a.user_id = $1
ORDER BY j.created_at DESC
LIMIT $2 OFFSET $3
`

type GetJobsByUserIDPaginatedParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Get paginated jobs for a specific user (through applications), ordered by created_at (newest first)
func (q *Queries) GetJobsByUserIDPaginated(ctx context.Context, arg GetJobsByUserIDPaginatedParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getJobsByUserIDPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Requirements,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET title = $2,
    description = $3,
    requirements = $4,
    location = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE jobs.id = $1
  AND EXISTS (
    SELECT 1 FROM applications a
    WHERE a.id = jobs.application_id AND a.user_id = $6
  )
RETURNING id, company_id, title, description, requirements, location, created_at, updated_at, application_id
`

type UpdateJobParams struct {
	ID           int32          `json:"id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	Requirements sql.NullString `json:"requirements"`
	Location     sql.NullString `json:"location"`
	UserID       int32          `json:"user_id"`
}

// Update a job and return the updated record (verifies ownership through application's user_id)
func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJob,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Requirements,
		arg.Location,
		arg.UserID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Requirements,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApplicationID,
	)
	return i, err
}
