// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: jobs.sql

package database

import (
	"context"
	"database/sql"
)

const countJobs = `-- name: CountJobs :one
SELECT COUNT(*) FROM jobs
`

// Get total count of jobs
func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (application_id, company_id, title, description, requirements, location)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, title, description, requirements, location, created_at, updated_at, application_id
`

type CreateJobParams struct {
	ApplicationID int32          `json:"application_id"`
	CompanyID     int32          `json:"company_id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	Requirements  sql.NullString `json:"requirements"`
	Location      sql.NullString `json:"location"`
}

// Create a new job and return the created record
// Jobs now belong to applications (application_id is required)
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.ApplicationID,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.Requirements,
		arg.Location,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Requirements,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApplicationID,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1
`

// Delete a job by ID
func (q *Queries) DeleteJob(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const getAllJobs = `-- name: GetAllJobs :many
SELECT id, company_id, title, description, requirements, location, created_at, updated_at, application_id FROM jobs
ORDER BY created_at DESC
`

// Get all jobs, ordered by created_at (newest first)
func (q *Queries) GetAllJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getAllJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Requirements,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllJobsPaginated = `-- name: GetAllJobsPaginated :many
SELECT id, company_id, title, description, requirements, location, created_at, updated_at, application_id FROM jobs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllJobsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Get paginated jobs, ordered by created_at (newest first)
func (q *Queries) GetAllJobsPaginated(ctx context.Context, arg GetAllJobsPaginatedParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getAllJobsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Requirements,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, company_id, title, description, requirements, location, created_at, updated_at, application_id FROM jobs
WHERE id = $1
`

// Get a single job by ID
func (q *Queries) GetJobByID(ctx context.Context, id int32) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Requirements,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApplicationID,
	)
	return i, err
}

const getJobsByApplicationID = `-- name: GetJobsByApplicationID :many
SELECT id, company_id, title, description, requirements, location, created_at, updated_at, application_id FROM jobs
WHERE application_id = $1
ORDER BY created_at DESC
`

// Get all jobs for a specific application (should typically be just one)
func (q *Queries) GetJobsByApplicationID(ctx context.Context, applicationID int32) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getJobsByApplicationID, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Requirements,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsByCompanyID = `-- name: GetJobsByCompanyID :many
SELECT id, company_id, title, description, requirements, location, created_at, updated_at, application_id FROM jobs
WHERE company_id = $1
ORDER BY created_at DESC
`

// Get all jobs for a specific company
func (q *Queries) GetJobsByCompanyID(ctx context.Context, companyID int32) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getJobsByCompanyID, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Requirements,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET title = $2,
    description = $3,
    requirements = $4,
    location = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, company_id, title, description, requirements, location, created_at, updated_at, application_id
`

type UpdateJobParams struct {
	ID           int32          `json:"id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	Requirements sql.NullString `json:"requirements"`
	Location     sql.NullString `json:"location"`
}

// Update a job and return the updated record
func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJob,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Requirements,
		arg.Location,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Requirements,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApplicationID,
	)
	return i, err
}
