// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Application struct {
	ID          int32          `json:"id"`
	Status      string         `json:"status"`
	AppliedDate time.Time      `json:"applied_date"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Company struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Website   sql.NullString `json:"website"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Job struct {
	ID            int32          `json:"id"`
	CompanyID     int32          `json:"company_id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	Requirements  sql.NullString `json:"requirements"`
	Location      sql.NullString `json:"location"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	ApplicationID int32          `json:"application_id"`
}
