// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Application struct {
	ID          int32          `json:"id"`
	Status      string         `json:"status"`
	AppliedDate time.Time      `json:"applied_date"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	ContactID   sql.NullInt32  `json:"contact_id"`
	UserID      int32          `json:"user_id"`
}

type Company struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Website   sql.NullString `json:"website"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	UserID    int32          `json:"user_id"`
}

type Contact struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Email     sql.NullString `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Linkedin  sql.NullString `json:"linkedin"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	UserID    int32          `json:"user_id"`
}

type Job struct {
	ID            int32          `json:"id"`
	CompanyID     int32          `json:"company_id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	Requirements  sql.NullString `json:"requirements"`
	Location      sql.NullString `json:"location"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	ApplicationID int32          `json:"application_id"`
}

type RefreshToken struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type User struct {
	ID           int32          `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         sql.NullString `json:"name"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	LastLogin    sql.NullTime   `json:"last_login"`
	ClerkUserID  sql.NullString `json:"clerk_user_id"`
}
