// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, name, created_at, updated_at, last_login, clerk_user_id
`

type CreateUserParams struct {
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         sql.NullString `json:"name"`
}

// Create a new user and return the created record
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.ClerkUserID,
	)
	return i, err
}

const createUserWithClerkID = `-- name: CreateUserWithClerkID :one
INSERT INTO users (clerk_user_id, email, password_hash, name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, created_at, updated_at, last_login, clerk_user_id
`

type CreateUserWithClerkIDParams struct {
	ClerkUserID  sql.NullString `json:"clerk_user_id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         sql.NullString `json:"name"`
}

// Create a user linked to Clerk (password_hash empty for Clerk-only users)
func (q *Queries) CreateUserWithClerkID(ctx context.Context, arg CreateUserWithClerkIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserWithClerkID,
		arg.ClerkUserID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.ClerkUserID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

// Delete a user by ID (CASCADE will delete all related data)
func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, email, password_hash, name, created_at, updated_at, last_login, clerk_user_id FROM users
WHERE clerk_user_id = $1
LIMIT 1
`

// Get a user by Clerk user id (for JWT sub resolution)
func (q *Queries) GetUserByClerkID(ctx context.Context, clerkUserID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByClerkID, clerkUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.ClerkUserID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, created_at, updated_at, last_login, clerk_user_id FROM users
WHERE LOWER(email) = LOWER($1)
LIMIT 1
`

// Get a user by email (case-insensitive)
func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.ClerkUserID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, created_at, updated_at, last_login, clerk_user_id FROM users
WHERE id = $1
`

// Get a user by ID
func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.ClerkUserID,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, password_hash, name, created_at, updated_at, last_login, clerk_user_id
`

type UpdateUserParams struct {
	ID   int32          `json:"id"`
	Name sql.NullString `json:"name"`
}

// Update user information
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.ClerkUserID,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login = CURRENT_TIMESTAMP
WHERE id = $1
`

// Update the last_login timestamp
func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, id)
	return err
}
